- hosts: centos8
  gather_facts: false
  tasks:
   - name: install apache
     yum: name=httpd
 

- name: Start instances
  hosts: centos8
  gather_facts: false
  tasks:
    - name: Start EC2 Info
      ec2:
        wait: True      
        instance_tags:
            Name: "{{ tag }}"
        state: running
        region: ap-northeast-1

    - name: Get EC2 Info
      ec2_instance_info:
        region: ap-northeast-1
        filters:
         "tag:Name": "{{ tag }}"
      register: Instance_State
      
    - name: result
      assert:
        that:
          - Instance_State.instances[0].state.name == "running"
        fail_msg: "ERROR"
        success_msg: "OK"   
