- name: Stop instances
  hosts: localhost
  tasks:
    - name: Stop webserver1
      ec2:
        wait: True
        instance_tags:
            Name: "{{ tag }}"
        state: running
        region: ap-northeast-1
      register: cmd_out

    - name: debug
      debug:
        var: cmd_out
