- name: Stop instances
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Stop webserver1
      ec2:
        wait: True      
        instance_tags:
            Name: "{{ tag }}"
        state: stopped
        region: ap-northeast-1
      register: cmd_out

    - name: Get EC2 Info
      ec2_instance_info:
        region: ap-northeast-1
        filters:
         "tag:Name": "{{ tag }}"
      register: Instance_ID
      
    - name: result
      assert:
        that:
          - Instance_ID.instances[0].state.name == "stopped"
        fail_msg: "ERROR"
        success_msg: "OK"        
