- name: Deregister
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get EC2 Info
      ec2_instance_info:
        region: ap-northeast-1
        filters:
         "tag:Name": "{{ tag }}"
      register: Instance_ID
