- name: Stop instances
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Gathering ELB facts
      elb_application_lb_info:
        region: ap-northeast-1
      register: elb_facts


    - name: Instance De-register
      ec2_elb:
        instance_id: "{{ ec2_instance_id }}"
        state: present
        region: ap-northeast-1
        wait: yes
      register: cmd_out

    - name: debug
      debug:
        var: cmd_out   
