- hosts: windows2019
  gather_facts: false
  tasks:
   - name: check-http
     win_shell: $w = Invoke-WebRequest -Uri "http://localhost" -UseBasicParsing ; $w.StatusCode | Select-String -Pattern 201 -Quiet
     register: cmdexe1_out
     
   - name: check-http >  out
     debug:
       var: cmdexe1_out.stdout_lines
       
   - name: result
     assert:
       that:
         - cmdexe1_out.stdout_lines[0] == "True"
       fail_msg: "error"
       success_msg: "OK"
    
