- name: Stop sandbox instances22222
  hosts: localhost
  gather_facts: false
  tasks:
    - name: create ec2 instance
      ec2:
        key_name: ssh-key
        instance_type: t2.micro
        image: ami-0992fc94ca0f1415a
        wait: yes
        group: sg-0e623d11e341abef0
        count: 1
        vpc_subnet_id: subnet-05dc3e954e7e6787c 
        assign_public_ip: yes
        region: ap-northeast-1
      register: ec2_regst

    - debug: var=ec2_regst
      when: ec2_regst | success
